name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # executa todo dia √† meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do reposit√≥rio
        uses: actions/checkout@v3

      - name: Gerar cobrinha SVG
        uses: Platane/snk@v3
        with:
          github_user_name: FelipeM1221
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e push do SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "üêç Atualizando cobrinha dos commits"
          add: "dist/*.svg"
